const LOCAL_STORAGE_TIMESTAMPS_KEY = "@LOCAL_STORAGE_TIMESTAMPS_KEY";
const MIN_SMILE_AMOUNT = 0.90; // [0, 1]
const TYPE_PERSON = 0;
const TYPE_CAR = 1;

export { LOCAL_STORAGE_TIMESTAMPS_KEY, MIN_SMILE_AMOUNT, TYPE_PERSON, TYPE_CAR };
